# ================================================================================================
# Dockerfile para produccion
# Codigo fuente local
# Version 1: Codigo fuente disponible localmente
# Se asume que tienes el Dockerfile en la misma carpeta que el codigo fuente de la app
# Uso:
# docker build -f Dockerfile-local -t gw2Angular-local .
# docker run -d -p 4201:80 --name gw2Angular-local --restart unless-stopped gw2Angular-local
# Abrir la app en http://localhost:4201
# ================================================================================================

# 1 Build de Angular
FROM node:16.20.2 AS build

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar todo el codigo fuente
COPY . .

# Compilar la app Angular en modo produccion
RUN npx ng build --configuration production

# 2 Servir con Nginx
FROM nginx:stable-alpine

# Copiar archivos compilados de Angular a Nginx
COPY --from=build /app/dist/gw2Angular /usr/share/nginx/html

# Copiar configuracion personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponer puerto 80
EXPOSE 80

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
